<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.15" />
      <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.17" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.17" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="src\StServer.Api\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Api\obj\StServer.Api.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Domain\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Domain\obj\StServer.Domain.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Api\Properties\launchSettings.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Api\obj\project.packagespec.json" />
      <_ContentIncludedByDefault Remove="src\StServer.Domain\obj\project.packagespec.json" />
    </ItemGroup>

    <ItemGroup>
      <None Include="src\Api\Properties\launchSettings.json" />
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\Domain\Utility\Assessment\" />
    </ItemGroup>

</Project>
